apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
#    role: nginx-pod
    app: nginx  #서비스를 만들때 이 이름으로 네트워크 설정 적용
spec:
  containers:
    - name: nginx-pod
      image: nginx:latest #도커 이미지
#      imagePullPolicy: IfNotPresent
      ports:
         - containerPort: 80
#        - name: nginx-pod
#          protocol: TCP
#  restartPolicy: Always
  